### ISSUE TITLE
Problem loading under ubuntu-latest and Github Actions Current runner version: '2.272.0'` 

### ISSUE THREAD

**Issue by codycoggins-virtru** [mbowman100/swagger-validator-action#7]
It appears that `mbowman100/swagger-validator-action` was unable to load. My workflow file follows the template closely.

The change I noticed is the Github Action runner version:
the last good run had `Current runner version: '2.267.1'`
Now the version is `Current runner version: '2.272.0'` and the following error blocks the validator from starting:
```
Download action repository 'mbowman100/swagger-validator-action@master'
##[error]mbowman100/swagger-validator-action/master/action.yaml (Line: 13, Col: 3): Unexpected value '<file name> is valid'
##[error]mbowman100/swagger-validator-action/master/action.yaml (Line: 13, Col: 3): Unexpected value '<file name> is valid'
##[error]System.ArgumentException: Unexpected type 'StringToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
##[error]Fail to load mbowman100/swagger-validator-action/master/action.yaml
```

Am I reading the situation correctly?  Is anyone else able to run the validator on 2.272.0 and ubuntu-latest?

**Comment by codycoggins-virtru** [comment]
Thank you @mbowman100 for the rapid fix!  Works in my repo now.
